default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: example_development


test:
  <<: *default
  database: example_test

staging:
  <<: *default
  database: example_staging

production:
  <<: *default
  database: example_production
  username: example
  password: <%= ENV['SG_DATABASE_PASSWORD'] %>
